version: '3'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  cpu-worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  gpu-worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile.gpu
    depends_on:
      - redis
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - REDIS_HOST=redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['0']
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
