apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      # nodeSelector:
      #   tier: cpu
      containers:
        - name: api
          image: autoscale-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: REDIS_HOST
              value: redis
---

# app service
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      protocol: TCP