apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-worker
spec:
  selector:
    matchLabels:
      app: gpu-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: gpu-worker
    spec:
      # nodeSelector:
      #   tier: gpu
      containers:
        - name: gpu-worker
          image: autoscale-gpu-worker
          resources:
            limits:
              nvidia.com/gpu: 1
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis